[[constraint]]
  name = "cloud.google.com/go"
  revision = "be58d9a00708167c7fc48efeb85a1cbf952a27be"

[[constraint]]
  name = "github.com/agext/levenshtein"
  revision = "5f10fee965225ac1eecdc234c09daf5cd9e7f7b6"

[[constraint]]
  name = "github.com/apparentlymart/go-cidr"
  revision = "7e4b007599d4e2076d9a81be723b3912852dda2c"

[[constraint]]
  name = "github.com/apparentlymart/go-textseg"
  revision = "b836f5c4d331d1945a2fead7188db25432d73b69"

[[constraint]]
  name = "github.com/armon/go-radix"
  revision = "1fca145dffbcaa8fe914309b1ec0cfc67500fe61"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.8.34"

[[constraint]]
  name = "github.com/bgentry/go-netrc"
  revision = "9fd32a8b3d3d3f9d43c341bfe098430e07609480"

[[constraint]]
  name = "github.com/bgentry/speakeasy"
  revision = "4aabc24848ce5fd31929f7d1e4ea74d3709c14cd"

[[constraint]]
  name = "github.com/blang/semver"
  revision = "2ee87856327ba09384cabd113bc6b5d174e9ec0f"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  revision = "346938d642f2ec3594ed81d874461961cd0faa76"

[[constraint]]
  name = "github.com/go-ini/ini"
  revision = "766e555c68dc8bda90d197ee8946c37519c19409"

[[constraint]]
  name = "github.com/golang/protobuf"
  revision = "5a0f697c9ed9d68fef0116532c6e05cfeae00e55"

[[constraint]]
  name = "github.com/golang/snappy"
  revision = "553a641470496b2327abcac10b36396bd98e45c9"

[[constraint]]
  name = "github.com/googleapis/gax-go"
  revision = "e6c452d1a33fcea46ab9cfd3058ee858297ac13a"

[[constraint]]
  name = "github.com/hashicorp/errwrap"
  revision = "7554cd9344cec97297fa6649b055a8c98c2a1e55"

[[constraint]]
  name = "github.com/hashicorp/go-cleanhttp"
  revision = "3573b8b52aa7b37b9358d966a898feb387f62437"

[[constraint]]
  name = "github.com/hashicorp/go-getter"
  revision = "961f56d2e93379b7d9c578e998d09257509a6f97"

[[constraint]]
  name = "github.com/hashicorp/go-hclog"
  revision = "ca137eb4b4389c9bc6f1a6d887f056bf16c00510"

[[constraint]]
  name = "github.com/hashicorp/go-multierror"
  revision = "d30f09973e19c1dfcd120b2d9c4f168e68d6b5d5"

[[constraint]]
  name = "github.com/hashicorp/go-plugin"
  revision = "e2fbc6864d18d3c37b6cde4297ec9fca266d28f1"

[[constraint]]
  name = "github.com/hashicorp/go-uuid"
  revision = "36289988d83ca270bc07c234c36f364b0dd9c9a7"

[[constraint]]
  name = "github.com/hashicorp/go-version"
  revision = "e96d3840402619007766590ecea8dd7af1292276"

[[constraint]]
  name = "github.com/hashicorp/hcl"
  revision = "a4b07c25de5ff55ad3b8936cea69a79a3d95a855"

[[constraint]]
  name = "github.com/hashicorp/hcl2"
  revision = "44bad6dbf5490f5da17ec991e664df3d017b706f"

[[constraint]]
  name = "github.com/hashicorp/hil"
  revision = "fac2259da677551de1fb92b844c4d020a38d8468"

[[constraint]]
  name = "github.com/hashicorp/logutils"
  revision = "0dc08b1671f34c4250ce212759ebd880f743d883"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  revision = "096847c9f774bfb946de7413260b30f9f6041241"

[[constraint]]
  name = "github.com/hashicorp/vault"
  revision = "6faf8365e922c4cf1bde05b6b886a17881b9ebca"

[[constraint]]
  name = "github.com/hashicorp/yamux"
  revision = "d1caa6c97c9fc1cc9e83bbe34d0603f9ff0ce8bd"

[[constraint]]
  name = "github.com/jmespath/go-jmespath"
  revision = "bd40a432e4c76585ef6b72d3fd96fb9b6dc7b68d"

[[constraint]]
  name = "github.com/keybase/go-crypto"
  revision = "433e2f3d43ef1bd31387582a899389b2fbe2005e"

[[constraint]]
  name = "github.com/mattn/go-isatty"
  revision = "6ca4dbf54d38eea1a992b3c722a76a5d1c4cb25c"

[[constraint]]
  name = "github.com/mitchellh/cli"
  revision = "65fcae5817c8600da98ada9d7edf26dd1a84837b"

[[constraint]]
  name = "github.com/mitchellh/copystructure"
  revision = "5af94aef99f597e6a9e1f6ac6be6ce0f3c96b49d"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  revision = "b8bc1bf767474819792c23f32d8286a45736f1c6"

[[constraint]]
  name = "github.com/mitchellh/go-testing-interface"
  revision = "a61a99592b77c9ba629d254a693acffaeb4b7e28"

[[constraint]]
  name = "github.com/mitchellh/go-wordwrap"
  revision = "ad45545899c7b13c020ea92b2072220eefad42b8"

[[constraint]]
  name = "github.com/mitchellh/hashstructure"
  revision = "6b17d669fac5e2f71c16658d781ec3fdd3802b69"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  revision = "53818660ed4955e899c0bcafa97299a388bd7c8e"

[[constraint]]
  name = "github.com/mitchellh/reflectwalk"
  revision = "92573fe8d000a145bfebc03a16bc22b34945867f"

[[constraint]]
  name = "github.com/posener/complete"
  revision = "dc2bc5a81accba8782bebea28628224643a8286a"

[[constraint]]
  name = "github.com/rancher/go-rancher"
  revision = "ec24b7f12fca9f78fbfcd62a0ea8bce14ade8792"

[[constraint]]
  name = "github.com/satori/go.uuid"
  revision = "b061729afc07e77a8aa4fad0a2fd840958f1942a"

[[constraint]]
  name = "github.com/ulikunitz/xz"
  revision = "0c6b41e72360850ca4f98dc341fd999726ea007f"

[[constraint]]
  name = "github.com/zclconf/go-cty"
  revision = "709e4033eeb037dc543dbc2048065dfb814ce316"

[[constraint]]
  name = "golang.org/x/crypto"
  revision = "b176d7def5d71bdd214203491f89843ed217f420"

[[constraint]]
  name = "golang.org/x/net"
  revision = "434ec0c7fe3742c984919a691b2018a6e9694425"

[[constraint]]
  name = "golang.org/x/oauth2"
  revision = "9a379c6b3e95a790ffc43293c2a78dee0d7b6e20"

[[constraint]]
  name = "golang.org/x/sys"
  revision = "d4266bc12aae0b4128952c889b769442fce5d2f1"

[[constraint]]
  name = "golang.org/x/text"
  revision = "e19ae1496984b1c655b8044a65c0300a3c878dd3"

[[constraint]]
  name = "google.golang.org/api"
  revision = "4f7dd2b006a4ffd9fd683c1c734d2fe91ca0ea1c"

[[constraint]]
  name = "google.golang.org/appengine"
  revision = "b667a5000b082e49c6c6d16867d376a12e9490cd"

[[constraint]]
  name = "google.golang.org/genproto"
  revision = "a8101f21cf983e773d0c1133ebc5424792003214"

[[constraint]]
  name = "google.golang.org/grpc"
  revision = "84158ac547c2e121582f5f37458e693e339f099b"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.6.1"
